// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYNRIQDEcaf1oVxdj2s8_td6tvN0RwCqw',
    appId: '1:326157211250:web:ed24f2ff5df91a835614eb',
    messagingSenderId: '326157211250',
    projectId: 'myfirstapp-2911',
    authDomain: 'myfirstapp-2911.firebaseapp.com',
    storageBucket: 'myfirstapp-2911.appspot.com',
    measurementId: 'G-2QMT793WSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgvHCn2rwr8gcHa9G5JcShcX0yFfWyKyk',
    appId: '1:326157211250:android:8ca01a3b2d1c6c015614eb',
    messagingSenderId: '326157211250',
    projectId: 'myfirstapp-2911',
    storageBucket: 'myfirstapp-2911.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwsE0iNrSbDiN5ikGQgJ4fUSV-6daNR44',
    appId: '1:326157211250:ios:25aa26a29a4cb8605614eb',
    messagingSenderId: '326157211250',
    projectId: 'myfirstapp-2911',
    storageBucket: 'myfirstapp-2911.appspot.com',
    androidClientId: '326157211250-682ueoq6s4n58brdeqj3sasu08gge3bn.apps.googleusercontent.com',
    iosClientId: '326157211250-kgikdg2fh7d452ghbmh45d4b2vpacuup.apps.googleusercontent.com',
    iosBundleId: 'com.example.nadarat',
  );

}